import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.181.1/build/three.module.js';
import * as CANNON from 'https://cdn.jsdelivr.net/npm/cannon-es@0.20.0/dist/cannon-es.js';

const $=s=>document.querySelector(s);
const canvas=$('#game'),statusEl=$('#status'),power=$('#powerControl'),powerText=$('#powerText');
const resetBtn=$('#resetBtn'),cameraBtn=$('#cameraBtn'),soundBtn=$('#soundBtn'),modeBtn=$('#modeBtn'),shootBtn=$('#shootBtn');
const spinPad=$('#spinPad'),spinDot=$('#spinDot'),spinText=$('#spinText');
const matchHud=$('#matchHud'),p1Card=$('#p1Card'),p2Card=$('#p2Card'),p1Group=$('#p1Group'),p2Group=$('#p2Group');

const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050807);scene.fog=new THREE.FogExp2(0x050807,.075);
const camera=new THREE.PerspectiveCamera(42,1,.05,50);
const views=[[0,3.65,3.95],[0,5.25,.06],[3.55,2.35,0]];let view=0;function applyCamera(){camera.position.set(...views[view]);camera.lookAt(0,.55,0)}applyCamera();
scene.add(new THREE.HemisphereLight(0xcdeaff,0x17110c,.55));const key=new THREE.SpotLight(0xfff2d2,78,10,.68,.55,1.2);key.position.set(0,4.7,0);key.target.position.set(0,.5,0);key.castShadow=true;scene.add(key,key.target);const rim=new THREE.PointLight(0x6d8cff,8,7);rim.position.set(-3,2,2.6);scene.add(rim);

const world=new CANNON.World({gravity:new CANNON.Vec3(0,-9.82,0)});world.broadphase=new CANNON.SAPBroadphase(world);world.allowSleep=true;world.solver.iterations=16;
const matBall=new CANNON.Material('ball'),matCloth=new CANNON.Material('cloth'),matRail=new CANNON.Material('rail');
world.addContactMaterial(new CANNON.ContactMaterial(matBall,matBall,{friction:.02,restitution:.96}));world.addContactMaterial(new CANNON.ContactMaterial(matBall,matCloth,{friction:.2,restitution:.03}));world.addContactMaterial(new CANNON.ContactMaterial(matBall,matRail,{friction:.07,restitution:.8}));
const table={w:2.84,h:1.42,y:.72,rail:.105},ballR=.05715,pocketR=.095,balls=[],rails=[];
const pockets=[[-table.w/2,-table.h/2],[0,-table.h/2-.005],[table.w/2,-table.h/2],[-table.w/2,table.h/2],[0,table.h/2+.005],[table.w/2,table.h/2]];
const box=(size,color,rough=.65,metal=.05)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...size),new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal}));m.castShadow=m.receiveShadow=true;return m};
const floor=box([8,.18,7],0x17130f,.92,0);floor.position.y=-.1;scene.add(floor);world.addBody(new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(4,.09,3.5)),position:new CANNON.Vec3(0,-.1,0)}));
const base=box([table.w+.42,.25,table.h+.42],0x3b1d0b,.42,.08);base.position.y=table.y-.18;scene.add(base);const cloth=box([table.w,.055,table.h],0x0d5b42,.9,0);cloth.position.y=table.y;scene.add(cloth);world.addBody(new CANNON.Body({mass:0,material:matCloth,shape:new CANNON.Box(new CANNON.Vec3(table.w/2,.0275,table.h/2)),position:new CANNON.Vec3(0,table.y,0)}));
function rail(x,z,sx,sz){const m=box([sx,.18,sz],0x47230d,.4,.06);m.position.set(x,table.y+.12,z);scene.add(m);const body=new CANNON.Body({mass:0,material:matRail,shape:new CANNON.Box(new CANNON.Vec3(sx/2,.09,sz/2)),position:new CANNON.Vec3(x,table.y+.12,z)});world.addBody(body);rails.push(body)}
const gap=.18;rail(-table.w/4-.04,-table.h/2-table.rail/2,table.w/2-gap,table.rail);rail(table.w/4+.04,-table.h/2-table.rail/2,table.w/2-gap,table.rail);rail(-table.w/4-.04,table.h/2+table.rail/2,table.w/2-gap,table.rail);rail(table.w/4+.04,table.h/2+table.rail/2,table.w/2-gap,table.rail);rail(-table.w/2-table.rail/2,-table.h/4-.03,table.rail,table.h/2-gap);rail(-table.w/2-table.rail/2,table.h/4+.03,table.rail,table.h/2-gap);rail(table.w/2+table.rail/2,-table.h/4-.03,table.rail,table.h/2-gap);rail(table.w/2+table.rail/2,table.h/4+.03,table.rail,table.h/2-gap);
for(const [x,z] of pockets){const r=new THREE.Mesh(new THREE.CylinderGeometry(pocketR*1.12,pocketR*1.12,.025,28),new THREE.MeshStandardMaterial({color:0x030303,roughness:.8}));r.position.set(x,table.y+.04,z);scene.add(r)}
const colors=[0xffffff,0xf5d90a,0x174fb9,0xd8241b,0x6a2aa8,0xee6b18,0x13834f,0x6f1919,0x111111,0xf5d90a,0x174fb9,0xd8241b,0x6a2aa8,0xee6b18,0x13834f,0x6f1919];
function texture(n,color){const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.fillStyle='#'+new THREE.Color(color).getHexString();g.fillRect(0,0,256,256);if(n>8){g.fillStyle='#f7f4ea';g.fillRect(0,62,256,132)}if(n>0){g.beginPath();g.arc(128,128,52,0,Math.PI*2);g.fillStyle='#f7f4ea';g.fill();g.fillStyle='#111';g.font='700 68px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(String(n),128,132)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function addBall(n,x,z){const mesh=new THREE.Mesh(new THREE.SphereGeometry(ballR,32,20),new THREE.MeshStandardMaterial({map:texture(n,colors[n]),roughness:.2}));mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);const body=new CANNON.Body({mass:.17,material:matBall,shape:new CANNON.Sphere(ballR),position:new CANNON.Vec3(x,table.y+.055+ballR,z),linearDamping:.045,angularDamping:.065,allowSleep:true,sleepSpeedLimit:.02,sleepTimeLimit:.7});world.addBody(body);balls.push({n,mesh,body,pocketed:false});return balls.at(-1)}
function clearBalls(){for(const b of balls){scene.remove(b.mesh);if(world.bodies.includes(b.body))world.removeBody(b.body)}balls.length=0}

let mode='practice',currentPlayer=0,groups=[null,null],shotPocketed=[],shotActive=false,scratch=false,gameOver=false,shotFirstObject=null;
const groupOf=n=>n>=1&&n<=7?'solid':n>=9&&n<=15?'stripe':null;const groupLabel=g=>g==='solid'?'SOLIDS 1–7':g==='stripe'?'STRIPES 9–15':'OPEN';
function updateHud(){matchHud.classList.toggle('hidden',mode!=='two');p1Card.classList.toggle('active',currentPlayer===0);p2Card.classList.toggle('active',currentPlayer===1);p1Group.textContent=groupLabel(groups[0]);p2Group.textContent=groupLabel(groups[1]);modeBtn.textContent=mode==='two'?'2P 8-BALL':'練習'}
function resetMatch(){currentPlayer=0;groups=[null,null];shotPocketed=[];shotActive=false;scratch=false;gameOver=false;shotFirstObject=null;updateHud()}
function rack(){clearBalls();addBall(0,-table.w*.29,0);const order=[1,9,2,10,8,3,11,4,12,5,13,6,14,7,15];let i=0,startX=table.w*.18,dx=ballR*1.76,dz=ballR*2.04;for(let row=0;row<5;row++)for(let j=0;j<=row;j++)addBall(order[i++],startX+row*dx,(j-row/2)*dz);resetMatch();statusEl.textContent=mode==='two'?'PLAYER 1 のブレイク':'台をなぞって方向を合わせます'}rack();

const aimLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0xffffff,dashSize:.08,gapSize:.04,transparent:true,opacity:.75}));scene.add(aimLine);const cueMesh=new THREE.Mesh(new THREE.CylinderGeometry(.011,.017,1.4,18),new THREE.MeshStandardMaterial({color:0xd7ad6d,roughness:.38}));cueMesh.rotation.z=Math.PI/2;cueMesh.castShadow=true;scene.add(cueMesh);
let aimAngle=0,spinX=0,spinY=0,aiming=false;
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),-(table.y+ballR+.06));
function cueBall(){return balls.find(b=>b.n===0&&!b.pocketed)}function allStopped(){return balls.every(b=>b.pocketed||b.body.velocity.length()<.045)}
function pointOnTable(e){const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const out=new THREE.Vector3();return ray.ray.intersectPlane(plane,out)?out:null}
function updateAim(){const cb=cueBall();if(!cb||!allStopped()||gameOver){aimLine.visible=cueMesh.visible=false;return}aimLine.visible=cueMesh.visible=true;const p=cb.mesh.position,dir=new THREE.Vector3(Math.cos(aimAngle),0,Math.sin(aimAngle));aimLine.geometry.setFromPoints([new THREE.Vector3(p.x,p.y+.015,p.z),new THREE.Vector3(p.x+dir.x*2.5,p.y+.015,p.z+dir.z*2.5)]);aimLine.computeLineDistances();cueMesh.position.set(p.x-dir.x*.78,p.y+.045,p.z-dir.z*.78);cueMesh.rotation.set(0,-aimAngle,Math.PI/2)}
canvas.addEventListener('pointerdown',e=>{if(gameOver||!allStopped())return;aiming=true;canvas.setPointerCapture(e.pointerId);const p=pointOnTable(e),cb=cueBall();if(p&&cb){aimAngle=Math.atan2(p.z-cb.mesh.position.z,p.x-cb.mesh.position.x);updateAim()}audio.ensure()});
canvas.addEventListener('pointermove',e=>{if(!aiming)return;const p=pointOnTable(e),cb=cueBall();if(p&&cb){aimAngle=Math.atan2(p.z-cb.mesh.position.z,p.x-cb.mesh.position.x);updateAim()}});canvas.addEventListener('pointerup',()=>aiming=false);
canvas.addEventListener('wheel',e=>{e.preventDefault();camera.position.multiplyScalar(1+Math.sign(e.deltaY)*.022);camera.position.clampLength(2.8,7);camera.lookAt(0,.55,0)},{passive:false});

function setSpinFromEvent(e){const r=spinPad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=(e.clientX-cx)/(r.width*.38),y=(cy-e.clientY)/(r.height*.38);const m=Math.hypot(x,y);if(m>1){x/=m;y/=m}spinX=x;spinY=y;spinDot.style.left=(50+x*38)+'%';spinDot.style.top=(50-y*38)+'%';const v=Math.abs(x)<.12&&Math.abs(y)<.12?'CENTER':`${y>.15?'TOP ':y<-.15?'DRAW ':''}${x>.15?'RIGHT':x<-.15?'LEFT':''}`.trim();spinText.textContent=v||'CENTER'}
let spinDragging=false;spinPad.addEventListener('pointerdown',e=>{spinDragging=true;spinPad.setPointerCapture(e.pointerId);setSpinFromEvent(e)});spinPad.addEventListener('pointermove',e=>{if(spinDragging)setSpinFromEvent(e)});spinPad.addEventListener('pointerup',()=>spinDragging=false);
power.addEventListener('input',()=>powerText.textContent=power.value+'%');

const audio={ctx:null,on:true,lastClack:0,ensure(){if(!this.on)return;if(!this.ctx)this.ctx=new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume()},tone(f,d,v,t='sine'){if(!this.on)return;this.ensure();const now=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=t;o.frequency.value=f;g.gain.setValueAtTime(v,now);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.connect(g).connect(this.ctx.destination);o.start(now);o.stop(now+d)},cue(p){this.tone(120+80*p,.05,.05+.07*p,'triangle')},clack(v){const n=performance.now();if(n-this.lastClack<26)return;this.lastClack=n;this.tone(450+Math.min(v,3)*100,.03,.018+Math.min(v,.15),'triangle')},pocket(){this.tone(110,.1,.07);setTimeout(()=>this.tone(72,.14,.045),45)}};
function shoot(){if(gameOver||!allStopped())return;const cb=cueBall(),p=Number(power.value)/100;if(!cb||p<.02)return;const dir=new THREE.Vector3(Math.cos(aimAngle),0,Math.sin(aimAngle));const impulse=.72+p*4.35;shotPocketed=[];scratch=false;shotActive=true;shotFirstObject=null;cb.body.wakeUp();cb.body.applyImpulse(new CANNON.Vec3(dir.x*impulse,0,dir.z*impulse));const rollAxis=new CANNON.Vec3(-dir.z,0,dir.x);const baseRoll=impulse/ballR*.18;cb.body.angularVelocity.set(rollAxis.x*(baseRoll+spinY*48),spinX*42,rollAxis.z*(baseRoll+spinY*48));audio.cue(p);statusEl.textContent=mode==='two'?`PLAYER ${currentPlayer+1} ショット`:'ショット';power.value=35;powerText.textContent='35%';updateAim()}
shootBtn.addEventListener('click',shoot);

world.addEventListener('beginContact',ev=>{const a=balls.find(b=>b.body===ev.bodyA),b=balls.find(b=>b.body===ev.bodyB);if(a&&b){const rel=ev.bodyA.velocity.vsub(ev.bodyB.velocity).length();if(rel>.18)audio.clack(rel);if(shotActive&&!shotFirstObject){if(a.n===0&&b.n!==0)shotFirstObject=b.n;if(b.n===0&&a.n!==0)shotFirstObject=a.n}}const cb=cueBall();if(cb&&(ev.bodyA===cb.body||ev.bodyB===cb.body)){const other=ev.bodyA===cb.body?ev.bodyB:ev.bodyA;if(rails.includes(other)&&Math.abs(cb.body.angularVelocity.y)>1){const v=cb.body.velocity,s=Math.sign(cb.body.angularVelocity.y),mag=Math.min(Math.abs(cb.body.angularVelocity.y)*.0007,.02);const len=Math.hypot(v.x,v.z)||1;cb.body.velocity.x+=-v.z/len*s*mag;cb.body.velocity.z+=v.x/len*s*mag}}});
function restoreCue(){const b=balls.find(x=>x.n===0);if(!b||!b.pocketed)return;b.pocketed=false;b.body.position.set(-table.w*.29,table.y+.055+ballR,0);b.body.velocity.setZero();b.body.angularVelocity.setZero();b.mesh.visible=true;if(!world.bodies.includes(b.body))world.addBody(b.body)}
function pocketCheck(){for(const b of balls){if(b.pocketed)continue;const p=b.body.position;for(const [x,z] of pockets){if(Math.hypot(p.x-x,p.z-z)<pocketR*.82){b.pocketed=true;b.mesh.visible=false;if(world.bodies.includes(b.body))world.removeBody(b.body);audio.pocket();if(shotActive){shotPocketed.push(b.n);if(b.n===0)scratch=true}break}}}}
function remainingFor(g){return balls.filter(b=>groupOf(b.n)===g&&!b.pocketed).length}
function resolveShot(){if(!shotActive)return;shotActive=false;if(mode!=='two'){if(scratch)restoreCue();updateAim();return}const object=shotPocketed.filter(n=>n!==0&&n!==8),eight=shotPocketed.includes(8),g=groups[currentPlayer];let foul=scratch;if(g&&shotFirstObject&&shotFirstObject!==8&&groupOf(shotFirstObject)!==g)foul=true;if(g&&remainingFor(g)>0&&shotFirstObject===8)foul=true;if(eight){const legal=g&&remainingFor(g)===0&&!foul;gameOver=true;statusEl.textContent=legal?`PLAYER ${currentPlayer+1} WIN!`:`PLAYER ${2-currentPlayer} WIN! 8番ファウル`;updateHud();return}if(!groups[currentPlayer]&&object.length){const first=groupOf(object[0]);if(first){groups[currentPlayer]=first;groups[1-currentPlayer]=first==='solid'?'stripe':'solid'}}const own=groups[currentPlayer],scored=object.some(n=>!own||groupOf(n)===own);if(foul){restoreCue();currentPlayer=1-currentPlayer;statusEl.textContent=`FOUL — PLAYER ${currentPlayer+1}`;}else if(scored){statusEl.textContent=`PLAYER ${currentPlayer+1} 続行`;}else{currentPlayer=1-currentPlayer;statusEl.textContent=`PLAYER ${currentPlayer+1} の番`;}updateHud();updateAim()}

resetBtn.addEventListener('click',()=>{audio.ensure();rack();updateAim()});cameraBtn.addEventListener('click',()=>{view=(view+1)%views.length;applyCamera();updateAim()});soundBtn.addEventListener('click',()=>{audio.on=!audio.on;soundBtn.textContent=audio.on?'SOUND ON':'SOUND OFF';if(audio.on)audio.ensure()});modeBtn.addEventListener('click',()=>{mode=mode==='practice'?'two':'practice';rack();updateHud();updateAim()});
let last=performance.now(),acc=0,wasMoving=false;const fixed=1/120;
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;acc+=dt;while(acc>=fixed){world.step(fixed);for(const b of balls){if(b.pocketed)continue;const v=b.body.velocity,s=Math.hypot(v.x,v.z);if(s<.01){v.x=v.z=0}else{const rr=Math.max(0,1-.23*fixed);v.x*=rr;v.z*=rr}if(Math.abs(v.y)<.025)v.y=0}pocketCheck();acc-=fixed}for(const b of balls){if(!b.pocketed){b.mesh.position.copy(b.body.position);b.mesh.quaternion.copy(b.body.quaternion)}}const moving=!allStopped();if(wasMoving&&!moving)resolveShot();wasMoving=moving;if(!moving&&!shotActive)updateAim();renderer.render(scene,camera)}requestAnimationFrame(animate);
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();updateHud();updateAim();
