import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.181.1/build/three.module.js';
import * as CANNON from 'https://cdn.jsdelivr.net/npm/cannon-es@0.20.0/dist/cannon-es.js';

const $=s=>document.querySelector(s);
const canvas=$('#game'),statusEl=$('#status'),power=$('#powerControl'),powerText=$('#powerText');
const resetBtn=$('#resetBtn'),cameraBtn=$('#cameraBtn'),soundBtn=$('#soundBtn'),musicBtn=$('#musicBtn'),modeBtn=$('#modeBtn'),shootBtn=$('#shootBtn');
const spinPad=$('#spinPad'),spinDot=$('#spinDot'),spinText=$('#spinText'),guideBtn=$('#guideBtn'),ballInHandBtn=$('#ballInHandBtn');
const matchHud=$('#matchHud'),p1Card=$('#p1Card'),p2Card=$('#p2Card'),p1Group=$('#p1Group'),p2Group=$('#p2Group'),gameLabel=$('#gameLabel');

const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050504);scene.fog=new THREE.FogExp2(0x070604,.052);
const camera=new THREE.PerspectiveCamera(42,1,.05,60);
const overviewViews=[[0,3.6,4.1],[0,5.2,.08],[3.8,2.5,.2]];let view=0,followCamera=true;
function overview(){camera.position.set(...overviewViews[view]);camera.lookAt(0,.55,0)}overview();

scene.add(new THREE.HemisphereLight(0xa8b7c4,0x120b07,.24));
const tableLamp=new THREE.SpotLight(0xffe8bd,105,11,.62,.52,1.15);tableLamp.position.set(0,4.45,0);tableLamp.target.position.set(0,.65,0);tableLamp.castShadow=true;tableLamp.shadow.mapSize.set(1024,1024);scene.add(tableLamp,tableLamp.target);
const warmFill=new THREE.PointLight(0xff9a54,10,8);warmFill.position.set(-3,2.4,-2.7);scene.add(warmFill);
const coolFill=new THREE.PointLight(0x547dff,6,7);coolFill.position.set(3.4,1.9,2.4);scene.add(coolFill);

const world=new CANNON.World({gravity:new CANNON.Vec3(0,-9.82,0)});world.broadphase=new CANNON.SAPBroadphase(world);world.allowSleep=true;world.solver.iterations=16;
const matBall=new CANNON.Material('ball'),matCloth=new CANNON.Material('cloth'),matRail=new CANNON.Material('rail');
world.addContactMaterial(new CANNON.ContactMaterial(matBall,matBall,{friction:.02,restitution:.96}));world.addContactMaterial(new CANNON.ContactMaterial(matBall,matCloth,{friction:.2,restitution:.03}));world.addContactMaterial(new CANNON.ContactMaterial(matBall,matRail,{friction:.07,restitution:.8}));

const table={w:2.84,h:1.42,y:.72,rail:.105},ballR=.05715,pocketR=.095,balls=[],rails=[];
const pockets=[[-table.w/2,-table.h/2],[0,-table.h/2-.005],[table.w/2,-table.h/2],[-table.w/2,table.h/2],[0,table.h/2+.005],[table.w/2,table.h/2]];
const box=(size,color,rough=.65,metal=.05)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...size),new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal}));m.castShadow=m.receiveShadow=true;return m};

// Billiards lounge environment
const roomFloor=box([10,.18,8],0x24140c,.82,0);roomFloor.position.y=-.12;scene.add(roomFloor);world.addBody(new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(5,.09,4)),position:new CANNON.Vec3(0,-.12,0)}));
for(let i=-10;i<=10;i++){const seam=new THREE.Mesh(new THREE.BoxGeometry(.012,.004,8),new THREE.MeshBasicMaterial({color:0x0d0805,transparent:true,opacity:.35}));seam.position.set(i*.45,-.025,0);scene.add(seam)}
const backWall=box([10,4,.18],0x15110f,.95,0);backWall.position.set(0,1.85,-4);scene.add(backWall);
const sideWall=box([.18,4,8],0x171210,.95,0);sideWall.position.set(-5,1.85,0);scene.add(sideWall);
const wainscot=box([9.7,1.15,.08],0x351b11,.58,.02);wainscot.position.set(0,.48,-3.88);scene.add(wainscot);
const bar=box([3.4,1.05,.72],0x3b2015,.45,.04);bar.position.set(2.75,.42,-3.15);scene.add(bar);
const barTop=box([3.65,.12,.9],0x65402c,.28,.08);barTop.position.set(2.75,1.0,-3.15);scene.add(barTop);
for(let i=0;i<8;i++){const bottle=box([.09,.36,.09],[0x556b2f,0x6d2f2f,0x342f7a,0x8c7138][i%4],.3,.08);bottle.position.set(1.45+i*.36,1.45,-3.65);scene.add(bottle)}
for(const x of [1.65,2.45,3.25,4.05]){const seat=new THREE.Mesh(new THREE.CylinderGeometry(.25,.25,.12,24),new THREE.MeshStandardMaterial({color:0x35211b,roughness:.38}));seat.position.set(x,.58,-2.55);scene.add(seat);const leg=box([.08,.52,.08],0x171717,.4,.45);leg.position.set(x,.28,-2.55);scene.add(leg)}
const sofa=box([2.2,.7,.75],0x171615,.55,.02);sofa.position.set(-3.35,.35,-3.15);scene.add(sofa);
const sofaBack=box([2.2,.85,.18],0x1b1918,.55,.02);sofaBack.position.set(-3.35,.78,-3.48);scene.add(sofaBack);
for(const x of [-.8,.8]){const shade=new THREE.Mesh(new THREE.ConeGeometry(.55,.36,28,1,true),new THREE.MeshStandardMaterial({color:0x17130f,roughness:.35,side:THREE.DoubleSide}));shade.position.set(x,3.25,0);scene.add(shade);const bulb=new THREE.PointLight(0xffd69b,10,4.2);bulb.position.set(x,3.0,0);scene.add(bulb)}
const neonMat=new THREE.MeshBasicMaterial({color:0x7de9c5});const neon=box([1.8,.06,.035],0x7de9c5,.2,.1);neon.position.set(-3.35,2.5,-3.88);scene.add(neon);

const base=box([table.w+.42,.25,table.h+.42],0x32170c,.38,.08);base.position.y=table.y-.18;scene.add(base);const cloth=box([table.w,.055,table.h],0x075f45,.88,0);cloth.position.y=table.y;scene.add(cloth);world.addBody(new CANNON.Body({mass:0,material:matCloth,shape:new CANNON.Box(new CANNON.Vec3(table.w/2,.0275,table.h/2)),position:new CANNON.Vec3(0,table.y,0)}));
function rail(x,z,sx,sz){const m=box([sx,.18,sz],0x3e1d0c,.34,.06);m.position.set(x,table.y+.12,z);scene.add(m);const body=new CANNON.Body({mass:0,material:matRail,shape:new CANNON.Box(new CANNON.Vec3(sx/2,.09,sz/2)),position:new CANNON.Vec3(x,table.y+.12,z)});world.addBody(body);rails.push(body)}
const gap=.18;rail(-table.w/4-.04,-table.h/2-table.rail/2,table.w/2-gap,table.rail);rail(table.w/4+.04,-table.h/2-table.rail/2,table.w/2-gap,table.rail);rail(-table.w/4-.04,table.h/2+table.rail/2,table.w/2-gap,table.rail);rail(table.w/4+.04,table.h/2+table.rail/2,table.w/2-gap,table.rail);rail(-table.w/2-table.rail/2,-table.h/4-.03,table.rail,table.h/2-gap);rail(-table.w/2-table.rail/2,table.h/4+.03,table.rail,table.h/2-gap);rail(table.w/2+table.rail/2,-table.h/4-.03,table.rail,table.h/2-gap);rail(table.w/2+table.rail/2,table.h/4+.03,table.rail,table.h/2-gap);
for(const [x,z] of pockets){const r=new THREE.Mesh(new THREE.CylinderGeometry(pocketR*1.12,pocketR*1.12,.025,28),new THREE.MeshStandardMaterial({color:0x020202,roughness:.8}));r.position.set(x,table.y+.04,z);scene.add(r)}

const colors=[0xffffff,0xf5d90a,0x174fb9,0xd8241b,0x6a2aa8,0xee6b18,0x13834f,0x6f1919,0x111111,0xf5d90a,0x174fb9,0xd8241b,0x6a2aa8,0xee6b18,0x13834f,0x6f1919];
function texture(n,color){const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.fillStyle='#'+new THREE.Color(color).getHexString();g.fillRect(0,0,256,256);if(n>8){g.fillStyle='#f7f4ea';g.fillRect(0,62,256,132)}if(n>0){g.beginPath();g.arc(128,128,52,0,Math.PI*2);g.fillStyle='#f7f4ea';g.fill();g.fillStyle='#111';g.font='700 68px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(String(n),128,132)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function addBall(n,x,z){const mesh=new THREE.Mesh(new THREE.SphereGeometry(ballR,32,20),new THREE.MeshStandardMaterial({map:texture(n,colors[n]),roughness:.18}));mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);const body=new CANNON.Body({mass:.17,material:matBall,shape:new CANNON.Sphere(ballR),position:new CANNON.Vec3(x,table.y+.055+ballR,z),linearDamping:.045,angularDamping:.065,allowSleep:true,sleepSpeedLimit:.02,sleepTimeLimit:.7});world.addBody(body);balls.push({n,mesh,body,pocketed:false});return balls.at(-1)}
function clearBalls(){for(const b of balls){scene.remove(b.mesh);if(world.bodies.includes(b.body))world.removeBody(b.body)}balls.length=0}

let mode='practice',currentPlayer=0,groups=[null,null],shotPocketed=[],shotActive=false,scratch=false,gameOver=false,shotFirstObject=null,ballInHand=false,guideOn=true;
const groupOf=n=>n>=1&&n<=7?'solid':n>=9&&n<=15?'stripe':null;const groupLabel=g=>g==='solid'?'SOLIDS 1–7':g==='stripe'?'STRIPES 9–15':'OPEN';
function updateHud(){const match=mode!=='practice';matchHud.classList.toggle('hidden',!match);p1Card.classList.toggle('active',currentPlayer===0);p2Card.classList.toggle('active',currentPlayer===1);p1Group.textContent=mode==='two9'?'LOWEST BALL':groupLabel(groups[0]);p2Group.textContent=mode==='two9'?'LOWEST BALL':groupLabel(groups[1]);gameLabel.textContent=mode==='two9'?'9 BALL':'8 BALL';modeBtn.textContent=mode==='practice'?'練習':mode==='two8'?'2P 8-BALL':'2P 9-BALL';ballInHandBtn.classList.toggle('hidden',!ballInHand);guideBtn.textContent=guideOn?'GUIDE ON':'GUIDE OFF'}
function resetMatch(){currentPlayer=0;groups=[null,null];shotPocketed=[];shotActive=false;scratch=false;gameOver=false;shotFirstObject=null;ballInHand=false;updateHud()}
function rack8(){addBall(0,-table.w*.29,0);const order=[1,9,2,10,8,3,11,4,12,5,13,6,14,7,15];let i=0,startX=table.w*.18,dx=ballR*1.76,dz=ballR*2.04;for(let row=0;row<5;row++)for(let j=0;j<=row;j++)addBall(order[i++],startX+row*dx,(j-row/2)*dz)}
function rack9(){addBall(0,-table.w*.29,0);const layout=[[1],[2,3],[4,9,5],[6,7],[8]];const startX=table.w*.18,dx=ballR*1.78,dz=ballR*2.04;let row=0;for(const nums of layout){for(let j=0;j<nums.length;j++){const z=(j-(nums.length-1)/2)*dz;addBall(nums[j],startX+row*dx,z)}row++}}
function rack(){clearBalls();mode==='two9'?rack9():rack8();resetMatch();statusEl.textContent=mode==='practice'?'台をなぞって方向を合わせます':`PLAYER 1 のブレイク — ${mode==='two9'?'9 BALL':'8 BALL'}`}
rack();

const aimLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0xffffff,dashSize:.08,gapSize:.04,transparent:true,opacity:.78}));scene.add(aimLine);const ghostBall=new THREE.Mesh(new THREE.RingGeometry(ballR*.95,ballR*1.05,32),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.45,side:THREE.DoubleSide}));ghostBall.rotation.x=-Math.PI/2;scene.add(ghostBall);
const cueMesh=new THREE.Mesh(new THREE.CylinderGeometry(.011,.017,1.42,18),new THREE.MeshStandardMaterial({color:0xd7ad6d,roughness:.34}));cueMesh.rotation.z=Math.PI/2;cueMesh.castShadow=true;scene.add(cueMesh);
let aimAngle=0,spinX=0,spinY=0,aiming=false,cueAnim=0;
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),-(table.y+ballR+.06));
function cueBall(){return balls.find(b=>b.n===0&&!b.pocketed)}function allStopped(){return balls.every(b=>b.pocketed||b.body.velocity.length()<.045)}
function pointOnTable(e){const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const out=new THREE.Vector3();return ray.ray.intersectPlane(plane,out)?out:null}
function validCuePos(x,z){if(Math.abs(x)>table.w/2-ballR*1.1||Math.abs(z)>table.h/2-ballR*1.1)return false;for(const b of balls){if(b.n===0||b.pocketed)continue;if(Math.hypot(b.body.position.x-x,b.body.position.z-z)<ballR*2.05)return false}for(const [px,pz] of pockets)if(Math.hypot(px-x,pz-z)<pocketR*1.1)return false;return true}
function moveCueBall(x,z){const cb=balls.find(b=>b.n===0);if(!cb||!validCuePos(x,z))return false;cb.pocketed=false;cb.mesh.visible=true;if(!world.bodies.includes(cb.body))world.addBody(cb.body);cb.body.position.set(x,table.y+.055+ballR,z);cb.body.velocity.setZero();cb.body.angularVelocity.setZero();cb.mesh.position.copy(cb.body.position);return true}
function firstHitPrediction(){const cb=cueBall();if(!cb)return null;const ox=cb.body.position.x,oz=cb.body.position.z,dx=Math.cos(aimAngle),dz=Math.sin(aimAngle);let best=null;for(const b of balls){if(b.n===0||b.pocketed)continue;const rx=b.body.position.x-ox,rz=b.body.position.z-oz,t=rx*dx+rz*dz;if(t<=0)continue;const perp2=rx*rx+rz*rz-t*t,rr=(ballR*2.02)**2;if(perp2>rr)continue;const hit=t-Math.sqrt(rr-perp2);if(hit>0&&(!best||hit<best.hit))best={hit,b}}return best}
function updateAim(){const cb=cueBall();if(!cb||!allStopped()||gameOver){aimLine.visible=cueMesh.visible=ghostBall.visible=false;return}const p=cb.mesh.position,dir=new THREE.Vector3(Math.cos(aimAngle),0,Math.sin(aimAngle));const pred=guideOn?firstHitPrediction():null,len=pred?pred.hit:2.5;aimLine.geometry.setFromPoints([new THREE.Vector3(p.x,p.y+.015,p.z),new THREE.Vector3(p.x+dir.x*len,p.y+.015,p.z+dir.z*len)]);aimLine.computeLineDistances();aimLine.visible=guideOn;ghostBall.visible=!!pred&&guideOn;if(pred)ghostBall.position.set(p.x+dir.x*pred.hit,p.y+.02,p.z+dir.z*pred.hit);const stroke=cueAnim>0?Math.sin(cueAnim*Math.PI)*.24:0;cueMesh.visible=true;cueMesh.position.set(p.x-dir.x*(.78+stroke),p.y+.045,p.z-dir.z*(.78+stroke));cueMesh.rotation.set(0,-aimAngle,Math.PI/2);if(followCamera&&view===0){camera.position.lerp(new THREE.Vector3(p.x-dir.x*2.15,1.42,p.z-dir.z*2.15),.12);camera.lookAt(p.x,p.y+.03,p.z)}}
canvas.addEventListener('pointerdown',e=>{if(gameOver||!allStopped())return;const p=pointOnTable(e);if(!p)return;if(ballInHand){if(moveCueBall(p.x,p.z)){statusEl.textContent='手球位置を選択中 — 「手球確定」で決定';updateAim()}return}aiming=true;canvas.setPointerCapture(e.pointerId);const cb=cueBall();if(cb){aimAngle=Math.atan2(p.z-cb.mesh.position.z,p.x-cb.mesh.position.x);updateAim()}audio.ensure()});
canvas.addEventListener('pointermove',e=>{if(!aiming||ballInHand)return;const p=pointOnTable(e),cb=cueBall();if(p&&cb){aimAngle=Math.atan2(p.z-cb.mesh.position.z,p.x-cb.mesh.position.x);updateAim()}});canvas.addEventListener('pointerup',()=>aiming=false);
canvas.addEventListener('wheel',e=>{e.preventDefault();followCamera=false;camera.position.multiplyScalar(1+Math.sign(e.deltaY)*.022);camera.position.clampLength(2.8,7);camera.lookAt(0,.55,0)},{passive:false});

function setSpinFromEvent(e){const r=spinPad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=(e.clientX-cx)/(r.width*.38),y=(cy-e.clientY)/(r.height*.38);const m=Math.hypot(x,y);if(m>1){x/=m;y/=m}spinX=x;spinY=y;spinDot.style.left=(50+x*38)+'%';spinDot.style.top=(50-y*38)+'%';spinText.textContent=Math.abs(x)<.12&&Math.abs(y)<.12?'CENTER':`${y>.15?'TOP ':y<-.15?'DRAW ':''}${x>.15?'RIGHT':x<-.15?'LEFT':''}`.trim()||'CENTER'}
let spinDragging=false;spinPad.addEventListener('pointerdown',e=>{spinDragging=true;spinPad.setPointerCapture(e.pointerId);setSpinFromEvent(e)});spinPad.addEventListener('pointermove',e=>{if(spinDragging)setSpinFromEvent(e)});spinPad.addEventListener('pointerup',()=>spinDragging=false);power.addEventListener('input',()=>powerText.textContent=power.value+'%');

const audio={ctx:null,on:true,musicOn:false,lastClack:0,musicTimer:null,ensure(){if(!this.on&&!this.musicOn)return;if(!this.ctx)this.ctx=new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume()},tone(f,d,v,t='sine'){if(!this.on)return;this.ensure();const now=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=t;o.frequency.value=f;g.gain.setValueAtTime(v,now);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.connect(g).connect(this.ctx.destination);o.start(now);o.stop(now+d)},cue(p){this.tone(120+80*p,.05,.05+.07*p,'triangle')},clack(v){const n=performance.now();if(n-this.lastClack<26)return;this.lastClack=n;this.tone(450+Math.min(v,3)*100,.03,.018+Math.min(v,.15),'triangle')},pocket(){this.tone(110,.1,.07);setTimeout(()=>this.tone(72,.14,.045),45)},musicToggle(){this.musicOn=!this.musicOn;this.ensure();musicBtn.textContent=this.musicOn?'JAZZ ON':'JAZZ OFF';if(this.musicOn)this.startJazz();else if(this.musicTimer){clearInterval(this.musicTimer);this.musicTimer=null}},startJazz(){if(this.musicTimer)return;const chord=()=>{if(!this.musicOn||!this.ctx)return;const roots=[110,130.81,146.83,98];const r=roots[Math.floor(Math.random()*roots.length)];for(const ratio of [1,1.19,1.5,1.78]){const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type='sine';o.frequency.value=r*ratio;g.gain.setValueAtTime(.008,t);g.gain.exponentialRampToValueAtTime(.0001,t+1.7);o.connect(g).connect(this.ctx.destination);o.start(t);o.stop(t+1.8)}};chord();this.musicTimer=setInterval(chord,1900)}};
function shoot(){if(gameOver||!allStopped()||ballInHand)return;const cb=cueBall(),p=Number(power.value)/100;if(!cb||p<.02)return;const dir=new THREE.Vector3(Math.cos(aimAngle),0,Math.sin(aimAngle)),impulse=.72+p*4.35;shotPocketed=[];scratch=false;shotActive=true;shotFirstObject=null;cueAnim=.001;setTimeout(()=>{cb.body.wakeUp();cb.body.applyImpulse(new CANNON.Vec3(dir.x*impulse,0,dir.z*impulse));const rollAxis=new CANNON.Vec3(-dir.z,0,dir.x),baseRoll=impulse/ballR*.18;cb.body.angularVelocity.set(rollAxis.x*(baseRoll+spinY*48),spinX*42,rollAxis.z*(baseRoll+spinY*48));audio.cue(p)},90);statusEl.textContent=mode==='practice'?'ショット':`PLAYER ${currentPlayer+1} ショット`;power.value=35;powerText.textContent='35%'}
shootBtn.addEventListener('click',shoot);
world.addEventListener('beginContact',ev=>{const a=balls.find(b=>b.body===ev.bodyA),b=balls.find(b=>b.body===ev.bodyB);if(a&&b){const rel=ev.bodyA.velocity.vsub(ev.bodyB.velocity).length();if(rel>.18)audio.clack(rel);if(shotActive&&!shotFirstObject){if(a.n===0&&b.n!==0)shotFirstObject=b.n;if(b.n===0&&a.n!==0)shotFirstObject=a.n}}const cb=cueBall();if(cb&&(ev.bodyA===cb.body||ev.bodyB===cb.body)){const other=ev.bodyA===cb.body?ev.bodyB:ev.bodyA;if(rails.includes(other)&&Math.abs(cb.body.angularVelocity.y)>1){const v=cb.body.velocity,s=Math.sign(cb.body.angularVelocity.y),mag=Math.min(Math.abs(cb.body.angularVelocity.y)*.0007,.02),len=Math.hypot(v.x,v.z)||1;cb.body.velocity.x+=-v.z/len*s*mag;cb.body.velocity.z+=v.x/len*s*mag}}});
function restoreCue(){moveCueBall(-table.w*.29,0)}
function pocketCheck(){for(const b of balls){if(b.pocketed)continue;for(const [x,z] of pockets){if(Math.hypot(b.body.position.x-x,b.body.position.z-z)<pocketR*.82){b.pocketed=true;b.mesh.visible=false;if(world.bodies.includes(b.body))world.removeBody(b.body);audio.pocket();if(shotActive){shotPocketed.push(b.n);if(b.n===0)scratch=true}break}}}}
function remainingFor(g){return balls.filter(b=>groupOf(b.n)===g&&!b.pocketed).length}
function lowestNineBall(){const nums=balls.filter(b=>b.n>0&&b.n<=9&&!b.pocketed).map(b=>b.n);return nums.length?Math.min(...nums):9}
function respotNine(){const b=balls.find(x=>x.n===9);if(!b)return;b.pocketed=false;b.mesh.visible=true;if(!world.bodies.includes(b.body))world.addBody(b.body);b.body.position.set(table.w*.18,table.y+.055+ballR,0);b.body.velocity.setZero();b.body.angularVelocity.setZero()}
function resolve9(){const nine=shotPocketed.includes(9),required=lowestNineBall(),foul=scratch||!shotFirstObject||shotFirstObject!==required;if(nine){if(!foul){gameOver=true;statusEl.textContent=`PLAYER ${currentPlayer+1} WIN! 9番を沈めました`;updateHud();return}respotNine()}if(foul){if(scratch)restoreCue();currentPlayer=1-currentPlayer;ballInHand=true;statusEl.textContent=`FOUL — PLAYER ${currentPlayer+1} ボールインハンド`;}else if(shotPocketed.some(n=>n>0)){statusEl.textContent=`PLAYER ${currentPlayer+1} 続行`;}else{currentPlayer=1-currentPlayer;statusEl.textContent=`PLAYER ${currentPlayer+1} の番`;}updateHud();updateAim()}
function resolve8(){const object=shotPocketed.filter(n=>n!==0&&n!==8),eight=shotPocketed.includes(8),g=groups[currentPlayer];let foul=scratch||!shotFirstObject;if(g&&shotFirstObject&&shotFirstObject!==8&&groupOf(shotFirstObject)!==g)foul=true;if(g&&remainingFor(g)>0&&shotFirstObject===8)foul=true;if(eight){const legal=g&&remainingFor(g)===0&&!foul;gameOver=true;statusEl.textContent=legal?`PLAYER ${currentPlayer+1} WIN!`:`PLAYER ${2-currentPlayer} WIN! 8番ファウル`;updateHud();return}if(!groups[currentPlayer]&&object.length&&!foul){const first=groupOf(object[0]);if(first){groups[currentPlayer]=first;groups[1-currentPlayer]=first==='solid'?'stripe':'solid'}}const own=groups[currentPlayer],scored=object.some(n=>!own||groupOf(n)===own);if(foul){if(scratch)restoreCue();currentPlayer=1-currentPlayer;ballInHand=true;statusEl.textContent=`FOUL — PLAYER ${currentPlayer+1} ボールインハンド`;}else if(scored){statusEl.textContent=`PLAYER ${currentPlayer+1} 続行`;}else{currentPlayer=1-currentPlayer;statusEl.textContent=`PLAYER ${currentPlayer+1} の番`;}updateHud();updateAim()}
function resolveShot(){if(!shotActive)return;shotActive=false;if(mode==='practice'){if(scratch){restoreCue();ballInHand=true}updateHud();updateAim();return}mode==='two9'?resolve9():resolve8()}

resetBtn.addEventListener('click',()=>{audio.ensure();rack();updateAim()});cameraBtn.addEventListener('click',()=>{if(view===0&&followCamera){followCamera=false;overview()}else{view=(view+1)%overviewViews.length;followCamera=view===0;if(!followCamera)overview()}updateAim()});soundBtn.addEventListener('click',()=>{audio.on=!audio.on;soundBtn.textContent=audio.on?'SOUND ON':'SOUND OFF';if(audio.on)audio.ensure()});musicBtn.addEventListener('click',()=>audio.musicToggle());modeBtn.addEventListener('click',()=>{mode=mode==='practice'?'two8':mode==='two8'?'two9':'practice';rack();updateHud();updateAim()});guideBtn.addEventListener('click',()=>{guideOn=!guideOn;updateHud();updateAim()});ballInHandBtn.addEventListener('click',()=>{if(ballInHand){ballInHand=false;statusEl.textContent=`PLAYER ${currentPlayer+1} 手球位置確定`;updateHud();updateAim()}});
let last=performance.now(),acc=0,wasMoving=false;const fixed=1/120;
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;acc+=dt;if(cueAnim>0){cueAnim+=dt*4.8;if(cueAnim>=1)cueAnim=0}while(acc>=fixed){world.step(fixed);for(const b of balls){if(b.pocketed)continue;const v=b.body.velocity,s=Math.hypot(v.x,v.z);if(s<.01){v.x=v.z=0}else{const rr=Math.max(0,1-.23*fixed);v.x*=rr;v.z*=rr}if(Math.abs(v.y)<.025)v.y=0}pocketCheck();acc-=fixed}for(const b of balls){if(!b.pocketed){b.mesh.position.copy(b.body.position);b.mesh.quaternion.copy(b.body.quaternion)}}const moving=!allStopped();if(wasMoving&&!moving)resolveShot();wasMoving=moving;if(!moving&&!shotActive)updateAim();renderer.render(scene,camera)}requestAnimationFrame(animate);
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();updateHud();updateAim();