import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.181.1/build/three.module.js';
import * as CANNON from 'https://cdn.jsdelivr.net/npm/cannon-es@0.20.0/dist/cannon-es.js';

const $=s=>document.querySelector(s);
const canvas=$('#game'),statusEl=$('#status'),power=$('#powerControl'),powerText=$('#powerText');
const resetBtn=$('#resetBtn'),soundBtn=$('#soundBtn'),musicBtn=$('#musicBtn'),modeBtn=$('#modeBtn'),shootBtn=$('#shootBtn');
const guideBtn=$('#guideBtn'),ballInHandBtn=$('#ballInHandBtn'),aimPad=$('#aimPad'),aimLeftBtn=$('#aimLeftBtn'),aimRightBtn=$('#aimRightBtn'),angleText=$('#angleText');
const spinPad=$('#spinPad'),spinDot=$('#spinDot'),spinText=$('#spinText');
const matchHud=$('#matchHud'),p1Card=$('#p1Card'),p2Card=$('#p2Card'),p1Group=$('#p1Group'),p2Group=$('#p2Group'),gameLabel=$('#gameLabel');
const axisButtons=[...document.querySelectorAll('[data-axis]')];

const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050504);scene.fog=new THREE.FogExp2(0x080604,.045);
const camera=new THREE.PerspectiveCamera(43,1,.05,80);

const cam={target:new THREE.Vector3(0,.72,0),yaw:.08,pitch:.72,distance:4.4,minDistance:2.25,maxDistance:8.2,mode:'browse',axis:'Y'};
function syncCamera(){
  const cp=Math.cos(cam.pitch),sp=Math.sin(cam.pitch),cy=Math.cos(cam.yaw),sy=Math.sin(cam.yaw);
  camera.position.set(cam.target.x+cam.distance*cp*sy,cam.target.y+cam.distance*sp,cam.target.z+cam.distance*cp*cy);
  camera.lookAt(cam.target);
}
syncCamera();
window.billiardsCamera={
  browse(){cam.mode='browse'},
  stance(){cam.mode='stance';const cb=cueBall();if(cb){const p=cb.mesh.position,dir=new THREE.Vector3(Math.cos(aimAngle),0,Math.sin(aimAngle));cam.target.set(p.x,p.y-.015,p.z);cam.distance=2.3;cam.pitch=.34;cam.yaw=Math.atan2(-dir.x,-dir.z)}syncCamera()},
  axis(a){cam.axis=a;axisButtons.forEach(b=>b.classList.toggle('active',b.dataset.axis===a))}
};
axisButtons.forEach(b=>b.addEventListener('click',()=>window.billiardsCamera.axis(b.dataset.axis)));

scene.add(new THREE.HemisphereLight(0xa8b7c4,0x150c08,.28));
const key=new THREE.SpotLight(0xffe8bd,112,12,.58,.55,1.15);key.position.set(0,4.6,.1);key.target.position.set(0,.7,0);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key,key.target);
const warm=new THREE.PointLight(0xff9950,11,8);warm.position.set(-3.4,2.6,-2.8);scene.add(warm);const cool=new THREE.PointLight(0x547dff,6,7);cool.position.set(3.5,2.1,2.5);scene.add(cool);

const world=new CANNON.World({gravity:new CANNON.Vec3(0,-9.82,0)});world.broadphase=new CANNON.SAPBroadphase(world);world.allowSleep=true;world.solver.iterations=18;
const matBall=new CANNON.Material('ball'),matCloth=new CANNON.Material('cloth'),matRail=new CANNON.Material('rail');
world.addContactMaterial(new CANNON.ContactMaterial(matBall,matBall,{friction:.018,restitution:.965}));world.addContactMaterial(new CANNON.ContactMaterial(matBall,matCloth,{friction:.19,restitution:.02}));world.addContactMaterial(new CANNON.ContactMaterial(matBall,matRail,{friction:.065,restitution:.81}));
const table={w:2.84,h:1.42,y:.78,rail:.115},ballR=.05715,pocketR=.098,balls=[],rails=[];
const pockets=[[-table.w/2,-table.h/2],[0,-table.h/2],[table.w/2,-table.h/2],[-table.w/2,table.h/2],[0,table.h/2],[table.w/2,table.h/2]];
const box=(s,c,r=.65,m=.05)=>{const x=new THREE.Mesh(new THREE.BoxGeometry(...s),new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m}));x.castShadow=x.receiveShadow=true;return x};

// Lounge + realistic commercial-style pool table proportions.
const roomFloor=box([10,.18,8],0x25150d,.82,0);roomFloor.position.y=-.12;scene.add(roomFloor);
for(let i=-10;i<=10;i++){const seam=box([.008,.004,8],0x100907,1,0);seam.position.set(i*.45,-.025,0);scene.add(seam)}
const back=box([10,4,.18],0x15110f,.95,0);back.position.set(0,1.85,-4);scene.add(back);const side=box([.18,4,8],0x171210,.95,0);side.position.set(-5,1.85,0);scene.add(side);
const bar=box([3.5,1.05,.72],0x3b2015,.45,.04);bar.position.set(2.8,.42,-3.15);scene.add(bar);const barTop=box([3.72,.11,.9],0x6b452f,.28,.08);barTop.position.set(2.8,1,-3.15);scene.add(barTop);

const wood=0x4b2412,wood2=0x2f160c,metal=0x8a785c,felt=0x0a6246;
const apron=box([table.w+.52,.34,table.h+.52],wood2,.34,.04);apron.position.y=table.y-.26;scene.add(apron);
const slate=box([table.w+.08,.09,table.h+.08],0x202020,.95,0);slate.position.y=table.y-.035;scene.add(slate);
const cloth=box([table.w,.052,table.h],felt,.94,0);cloth.position.y=table.y;scene.add(cloth);
world.addBody(new CANNON.Body({mass:0,material:matCloth,shape:new CANNON.Box(new CANNON.Vec3(table.w/2,.026,table.h/2)),position:new CANNON.Vec3(0,table.y,0)}));

for(const [x,z] of [[-1.24,-.53],[1.24,-.53],[-1.24,.53],[1.24,.53]]){
  const leg=box([.22,.78,.22],wood,.32,.02);leg.position.set(x,.32,z);scene.add(leg);
  const foot=new THREE.Mesh(new THREE.CylinderGeometry(.14,.16,.08,28),new THREE.MeshStandardMaterial({color:0x161616,roughness:.35,metalness:.35}));foot.position.set(x,-.07,z);scene.add(foot);
}
function rail(x,z,sx,sz){const m=box([sx,.20,sz],wood,.31,.05);m.position.set(x,table.y+.13,z);scene.add(m);const cap=box([sx*.97,.045,sz*.97],0x6a3319,.28,.06);cap.position.set(x,table.y+.235,z);scene.add(cap);const b=new CANNON.Body({mass:0,material:matRail,shape:new CANNON.Box(new CANNON.Vec3(sx/2,.1,sz/2)),position:new CANNON.Vec3(x,table.y+.13,z)});world.addBody(b);rails.push(b)}
const gap=.20;rail(-table.w/4-.045,-table.h/2-table.rail/2,table.w/2-gap,table.rail);rail(table.w/4+.045,-table.h/2-table.rail/2,table.w/2-gap,table.rail);rail(-table.w/4-.045,table.h/2+table.rail/2,table.w/2-gap,table.rail);rail(table.w/4+.045,table.h/2+table.rail/2,table.w/2-gap,table.rail);rail(-table.w/2-table.rail/2,-table.h/4-.035,table.rail,table.h/2-gap);rail(-table.w/2-table.rail/2,table.h/4+.035,table.rail,table.h/2-gap);rail(table.w/2+table.rail/2,-table.h/4-.035,table.rail,table.h/2-gap);rail(table.w/2+table.rail/2,table.h/4+.035,table.rail,table.h/2-gap);

// Leather pockets, brass collars and sight diamonds.
for(const [x,z] of pockets){
  const cup=new THREE.Mesh(new THREE.CylinderGeometry(pocketR*1.05,pocketR*.82,.16,30,1,true),new THREE.MeshStandardMaterial({color:0x080706,roughness:.7,side:THREE.DoubleSide}));cup.position.set(x,table.y-.035,z);scene.add(cup);
  const ring=new THREE.Mesh(new THREE.TorusGeometry(pocketR*.92,.012,8,28),new THREE.MeshStandardMaterial({color:metal,roughness:.27,metalness:.48}));ring.rotation.x=Math.PI/2;ring.position.set(x,table.y+.045,z);scene.add(ring);
}
for(const sideZ of [-1,1])for(const x of [-1.05,-.53,.53,1.05]){const d=new THREE.Mesh(new THREE.OctahedronGeometry(.018),new THREE.MeshStandardMaterial({color:0xe7dbc4,roughness:.18}));d.scale.set(1,.22,.7);d.position.set(x,table.y+.246,sideZ*(table.h/2+table.rail*.5));scene.add(d)}

const colors=[0xffffff,0xf5d90a,0x174fb9,0xd8241b,0x6a2aa8,0xee6b18,0x13834f,0x6f1919,0x111111,0xf5d90a,0x174fb9,0xd8241b,0x6a2aa8,0xee6b18,0x13834f,0x6f1919];
function texture(n,c){const cv=document.createElement('canvas');cv.width=cv.height=256;const g=cv.getContext('2d');g.fillStyle='#'+new THREE.Color(c).getHexString();g.fillRect(0,0,256,256);if(n>8){g.fillStyle='#f7f4ea';g.fillRect(0,62,256,132)}if(n>0){g.beginPath();g.arc(128,128,52,0,Math.PI*2);g.fillStyle='#f7f4ea';g.fill();g.fillStyle='#111';g.font='700 68px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(String(n),128,132)}const t=new THREE.CanvasTexture(cv);t.colorSpace=THREE.SRGBColorSpace;return t}
function addBall(n,x,z){const mesh=new THREE.Mesh(new THREE.SphereGeometry(ballR,32,22),new THREE.MeshPhysicalMaterial({map:texture(n,colors[n]),roughness:.12,clearcoat:.45,clearcoatRoughness:.16}));mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);const body=new CANNON.Body({mass:.17,material:matBall,shape:new CANNON.Sphere(ballR),position:new CANNON.Vec3(x,table.y+.055+ballR,z),linearDamping:.045,angularDamping:.06,allowSleep:true,sleepSpeedLimit:.02,sleepTimeLimit:.7});world.addBody(body);balls.push({n,mesh,body,pocketed:false,falling:false,fallT:0,fallStart:null,fallPocket:null});return balls.at(-1)}
function clearBalls(){for(const b of balls){scene.remove(b.mesh);if(world.bodies.includes(b.body))world.removeBody(b.body)}balls.length=0}

let mode='practice',currentPlayer=0,groups=[null,null],shotPocketed=[],shotActive=false,scratch=false,gameOver=false,shotFirstObject=null,ballInHand=false,guideOn=true;
const groupOf=n=>n>=1&&n<=7?'solid':n>=9&&n<=15?'stripe':null,groupLabel=g=>g==='solid'?'SOLIDS 1–7':g==='stripe'?'STRIPES 9–15':'OPEN';
function updateHud(){const match=mode!=='practice';matchHud.classList.toggle('hidden',!match);p1Card.classList.toggle('active',currentPlayer===0);p2Card.classList.toggle('active',currentPlayer===1);p1Group.textContent=mode==='two9'?'LOWEST BALL':groupLabel(groups[0]);p2Group.textContent=mode==='two9'?'LOWEST BALL':groupLabel(groups[1]);gameLabel.textContent=mode==='two9'?'9 BALL':'8 BALL';modeBtn.textContent=mode==='practice'?'練習':mode==='two8'?'2P 8-BALL':'2P 9-BALL';ballInHandBtn.classList.toggle('hidden',!ballInHand);guideBtn.textContent=guideOn?'GUIDE ON':'GUIDE OFF';shootBtn.disabled=ballInHand||gameOver}
function resetMatch(){currentPlayer=0;groups=[null,null];shotPocketed=[];shotActive=false;scratch=false;gameOver=false;shotFirstObject=null;ballInHand=false;updateHud()}
function rack8(){addBall(0,-table.w*.29,0);const order=[1,9,2,10,8,3,11,4,12,5,13,6,14,7,15];let i=0,start=table.w*.18,dx=ballR*1.76,dz=ballR*2.04;for(let row=0;row<5;row++)for(let j=0;j<=row;j++)addBall(order[i++],start+row*dx,(j-row/2)*dz)}
function rack9(){addBall(0,-table.w*.29,0);const layout=[[1],[2,3],[4,9,5],[6,7],[8]],start=table.w*.18,dx=ballR*1.78,dz=ballR*2.04;layout.forEach((row,i)=>row.forEach((n,j)=>addBall(n,start+i*dx,(j-(row.length-1)/2)*dz)))}
function rack(){clearBalls();mode==='two9'?rack9():rack8();resetMatch();aimAngle=0;statusEl.textContent=mode==='practice'?'盤面を自由に見てから構えます':`PLAYER 1 のブレイク — ${mode==='two9'?'9 BALL':'8 BALL'}`;cam.target.set(0,.72,0);cam.distance=4.4;cam.pitch=.72;syncCamera();updateAim()}

const aimLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0xffffff,dashSize:.08,gapSize:.04,transparent:true,opacity:.78}));scene.add(aimLine);const ghost=new THREE.Mesh(new THREE.RingGeometry(ballR*.95,ballR*1.05,32),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.45,side:THREE.DoubleSide}));ghost.rotation.x=-Math.PI/2;scene.add(ghost);
const cueMesh=new THREE.Mesh(new THREE.CylinderGeometry(.0105,.017,1.48,18),new THREE.MeshPhysicalMaterial({color:0xc49a60,roughness:.28,clearcoat:.35}));cueMesh.rotation.z=Math.PI/2;cueMesh.castShadow=true;scene.add(cueMesh);
let aimAngle=0,spinX=0,spinY=0,cueAnim=0,aimDragging=false,aimStartX=0,aimStartAngle=0;
function cueBall(){return balls.find(b=>b.n===0&&!b.pocketed&&!b.falling)}function allStopped(){return balls.every(b=>b.pocketed||b.falling||b.body.velocity.length()<.045)}
function validCuePos(x,z){if(Math.abs(x)>table.w/2-ballR*1.1||Math.abs(z)>table.h/2-ballR*1.1)return false;for(const b of balls){if(b.n===0||b.pocketed||b.falling)continue;if(Math.hypot(b.body.position.x-x,b.body.position.z-z)<ballR*2.05)return false}return true}
function firstHitPrediction(){const cb=cueBall();if(!cb)return null;const ox=cb.body.position.x,oz=cb.body.position.z,dx=Math.cos(aimAngle),dz=Math.sin(aimAngle);let best=null;for(const b of balls){if(b.n===0||b.pocketed||b.falling)continue;const rx=b.body.position.x-ox,rz=b.body.position.z-oz,t=rx*dx+rz*dz;if(t<=0)continue;const p2=rx*rx+rz*rz-t*t,rr=(ballR*2.02)**2;if(p2>rr)continue;const hit=t-Math.sqrt(rr-p2);if(hit>0&&(!best||hit<best.hit))best={hit,b}}return best}
function normalizeAngle(){while(aimAngle>Math.PI)aimAngle-=Math.PI*2;while(aimAngle<-Math.PI)aimAngle+=Math.PI*2;angleText.textContent=(aimAngle*180/Math.PI).toFixed(1)+'°'}
function updateAim(){normalizeAngle();const cb=cueBall();if(!cb||!allStopped()||gameOver){aimLine.visible=cueMesh.visible=ghost.visible=false;return}const p=cb.mesh.position,dir=new THREE.Vector3(Math.cos(aimAngle),0,Math.sin(aimAngle)),pred=guideOn?firstHitPrediction():null,len=pred?pred.hit:2.5;aimLine.geometry.setFromPoints([new THREE.Vector3(p.x,p.y+.015,p.z),new THREE.Vector3(p.x+dir.x*len,p.y+.015,p.z+dir.z*len)]);aimLine.computeLineDistances();const aimingPhase=document.body.dataset.phase==='aim'||document.body.dataset.phase==='pull';aimLine.visible=guideOn&&aimingPhase;ghost.visible=!!pred&&guideOn&&aimingPhase;if(pred)ghost.position.set(p.x+dir.x*pred.hit,p.y+.02,p.z+dir.z*pred.hit);const stroke=cueAnim>0?Math.sin(cueAnim*Math.PI)*.24:0;cueMesh.visible=aimingPhase;cueMesh.position.set(p.x-dir.x*(.78+stroke),p.y+.05,p.z-dir.z*(.78+stroke));cueMesh.rotation.set(0,-aimAngle,Math.PI/2);if(cam.mode==='stance'){cam.target.set(p.x,p.y-.01,p.z);cam.yaw=Math.atan2(dir.x,dir.z)+Math.PI;syncCamera()}}

aimPad.addEventListener('pointerdown',e=>{if(gameOver||!allStopped()||ballInHand)return;aimDragging=true;aimStartX=e.clientX;aimStartAngle=aimAngle;aimPad.setPointerCapture(e.pointerId)});aimPad.addEventListener('pointermove',e=>{if(!aimDragging)return;aimAngle=aimStartAngle-(e.clientX-aimStartX)*.0042;updateAim()});aimPad.addEventListener('pointerup',()=>aimDragging=false);aimPad.addEventListener('pointercancel',()=>aimDragging=false);const fineStep=Math.PI/360;aimLeftBtn.addEventListener('click',()=>{aimAngle+=fineStep;updateAim()});aimRightBtn.addEventListener('click',()=>{aimAngle-=fineStep;updateAim()});

const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),-(table.y+ballR+.06));
function pointOnTable(e){const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const out=new THREE.Vector3();return ray.ray.intersectPlane(plane,out)?out:null}
canvas.addEventListener('pointerdown',e=>{if(!ballInHand||!allStopped())return;const p=pointOnTable(e),cb=balls.find(b=>b.n===0);if(!p||!cb||!validCuePos(p.x,p.z))return;cb.pocketed=false;cb.falling=false;cb.mesh.visible=true;if(!world.bodies.includes(cb.body))world.addBody(cb.body);cb.body.position.set(p.x,table.y+.055+ballR,p.z);cb.body.velocity.setZero();cb.body.angularVelocity.setZero();statusEl.textContent='手球位置を選択中 — 「手球位置を確定」で決定';updateAim()});

function setSpin(e){const r=spinPad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=(e.clientX-cx)/(r.width*.38),y=(cy-e.clientY)/(r.height*.38);const m=Math.hypot(x,y);if(m>1){x/=m;y/=m}spinX=x;spinY=y;spinDot.style.left=(50+x*38)+'%';spinDot.style.top=(50-y*38)+'%';spinText.textContent=Math.abs(x)<.12&&Math.abs(y)<.12?'CENTER':`${y>.15?'TOP ':y<-.15?'DRAW ':''}${x>.15?'RIGHT':x<-.15?'LEFT':''}`.trim()||'CENTER'}
let spinDragging=false;spinPad.addEventListener('pointerdown',e=>{spinDragging=true;spinPad.setPointerCapture(e.pointerId);setSpin(e)});spinPad.addEventListener('pointermove',e=>{if(spinDragging)setSpin(e)});spinPad.addEventListener('pointerup',()=>spinDragging=false);power.addEventListener('input',()=>powerText.textContent=power.value+'%');

const audio={ctx:null,on:true,musicOn:false,last:0,timer:null,ensure(){if(!this.ctx)this.ctx=new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume()},tone(f,d,v,t='sine'){if(!this.on)return;this.ensure();const n=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=t;o.frequency.value=f;g.gain.setValueAtTime(v,n);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g).connect(this.ctx.destination);o.start(n);o.stop(n+d)},cue(p){this.tone(120+80*p,.05,.05+.07*p,'triangle')},clack(v){const n=performance.now();if(n-this.last<26)return;this.last=n;this.tone(450+Math.min(v,3)*100,.03,.018+Math.min(v,.15),'triangle')},pocket(){this.tone(98,.12,.07);setTimeout(()=>this.tone(66,.18,.04),55)},musicToggle(){this.musicOn=!this.musicOn;musicBtn.textContent=this.musicOn?'JAZZ ON':'JAZZ OFF';if(this.musicOn){this.ensure();if(!this.timer)this.timer=setInterval(()=>{if(!this.musicOn)return;[110,130.8,146.8,98].forEach((f,i)=>setTimeout(()=>this.tone(f,1.2,.005,'sine'),i*120))},2100)}else if(this.timer){clearInterval(this.timer);this.timer=null}}};
function shoot(){if(gameOver||!allStopped()||ballInHand)return;const cb=cueBall(),p=Number(power.value)/100;if(!cb||p<.02)return;const dir=new THREE.Vector3(Math.cos(aimAngle),0,Math.sin(aimAngle)),impulse=.72+p*4.35;shotPocketed=[];scratch=false;shotActive=true;shotFirstObject=null;cueAnim=.001;shootBtn.disabled=true;setTimeout(()=>{cb.body.wakeUp();cb.body.applyImpulse(new CANNON.Vec3(dir.x*impulse,0,dir.z*impulse));const rollAxis=new CANNON.Vec3(-dir.z,0,dir.x),baseRoll=impulse/ballR*.18;cb.body.angularVelocity.set(rollAxis.x*(baseRoll+spinY*48),spinX*42,rollAxis.z*(baseRoll+spinY*48));audio.cue(p)},90);statusEl.textContent=mode==='practice'?'ショット':`PLAYER ${currentPlayer+1} ショット`;power.value=35;powerText.textContent='35%'}shootBtn.addEventListener('click',shoot);
world.addEventListener('beginContact',ev=>{const a=balls.find(b=>b.body===ev.bodyA),b=balls.find(b=>b.body===ev.bodyB);if(a&&b){const rel=ev.bodyA.velocity.vsub(ev.bodyB.velocity).length();if(rel>.18)audio.clack(rel);if(shotActive&&!shotFirstObject){if(a.n===0&&b.n!==0)shotFirstObject=b.n;if(b.n===0&&a.n!==0)shotFirstObject=a.n}}});

function startPocketFall(b,px,pz){if(b.falling||b.pocketed)return;b.falling=true;b.fallT=0;b.fallStart=b.mesh.position.clone();b.fallPocket=new THREE.Vector3(px,table.y-.24,pz);if(world.bodies.includes(b.body))world.removeBody(b.body);audio.pocket();if(shotActive){shotPocketed.push(b.n);if(b.n===0)scratch=true}}
function pocketCheck(){for(const b of balls){if(b.pocketed||b.falling)continue;for(const [x,z] of pockets){if(Math.hypot(b.body.position.x-x,b.body.position.z-z)<pocketR*.78){startPocketFall(b,x,z);break}}}}
function animatePocketFalls(dt){for(const b of balls){if(!b.falling)continue;b.fallT+=dt;const t=Math.min(1,b.fallT/.34),ease=t*t*(3-2*t);b.mesh.position.lerpVectors(b.fallStart,b.fallPocket,ease);b.mesh.rotation.x+=dt*8;b.mesh.rotation.z+=dt*5;if(t>=1){b.falling=false;b.pocketed=true;b.mesh.visible=false}}}
function restoreCue(){const b=balls.find(x=>x.n===0);if(!b)return;b.pocketed=false;b.falling=false;b.mesh.visible=true;if(!world.bodies.includes(b.body))world.addBody(b.body);b.body.position.set(-table.w*.29,table.y+.055+ballR,0);b.body.velocity.setZero();b.body.angularVelocity.setZero();b.mesh.position.copy(b.body.position)}
function remainingFor(g){return balls.filter(b=>groupOf(b.n)===g&&!b.pocketed&&!b.falling).length}
function lowestNineAtShot(){const nums=balls.filter(b=>b.n>0&&b.n<=9&&(!b.pocketed||shotPocketed.includes(b.n))).map(b=>b.n);return nums.length?Math.min(...nums):9}
function respotNine(){const b=balls.find(x=>x.n===9);if(!b)return;b.pocketed=false;b.falling=false;b.mesh.visible=true;if(!world.bodies.includes(b.body))world.addBody(b.body);b.body.position.set(table.w*.18,table.y+.055+ballR,0);b.body.velocity.setZero();b.body.angularVelocity.setZero();b.mesh.position.copy(b.body.position)}
function resolve9(){const nine=shotPocketed.includes(9),required=lowestNineAtShot(),foul=scratch||!shotFirstObject||shotFirstObject!==required;if(nine){if(!foul){gameOver=true;statusEl.textContent=`PLAYER ${currentPlayer+1} WIN! 9番を沈めました`;updateHud();return}respotNine()}if(foul){if(scratch)restoreCue();currentPlayer=1-currentPlayer;ballInHand=true;statusEl.textContent=`FOUL — PLAYER ${currentPlayer+1} ボールインハンド`;}else if(shotPocketed.some(n=>n>0)){statusEl.textContent=`PLAYER ${currentPlayer+1} 続行`;}else{currentPlayer=1-currentPlayer;statusEl.textContent=`PLAYER ${currentPlayer+1} の番`}updateHud()}
function resolve8(){const object=shotPocketed.filter(n=>n!==0&&n!==8),eight=shotPocketed.includes(8),g=groups[currentPlayer];let foul=scratch||!shotFirstObject;if(g&&shotFirstObject&&shotFirstObject!==8&&groupOf(shotFirstObject)!==g)foul=true;if(g&&remainingFor(g)>0&&shotFirstObject===8)foul=true;if(eight){const legal=g&&remainingFor(g)===0&&!foul;gameOver=true;statusEl.textContent=legal?`PLAYER ${currentPlayer+1} WIN!`:`PLAYER ${2-currentPlayer} WIN! 8番ファウル`;updateHud();return}if(!groups[currentPlayer]&&object.length&&!foul){const first=groupOf(object[0]);if(first){groups[currentPlayer]=first;groups[1-currentPlayer]=first==='solid'?'stripe':'solid'}}const own=groups[currentPlayer],scored=object.some(n=>!own||groupOf(n)===own);if(foul){if(scratch)restoreCue();currentPlayer=1-currentPlayer;ballInHand=true;statusEl.textContent=`FOUL — PLAYER ${currentPlayer+1} ボールインハンド`;}else if(scored){statusEl.textContent=`PLAYER ${currentPlayer+1} 続行`;}else{currentPlayer=1-currentPlayer;statusEl.textContent=`PLAYER ${currentPlayer+1} の番`}updateHud()}
function resolveShot(){if(!shotActive)return;shotActive=false;if(mode==='practice'){if(scratch){restoreCue();ballInHand=true;statusEl.textContent='スクラッチ — 手球を置いてください'}updateHud();return}mode==='two9'?resolve9():resolve8()}

resetBtn.addEventListener('click',()=>{audio.ensure();rack()});soundBtn.addEventListener('click',()=>{audio.on=!audio.on;soundBtn.textContent=audio.on?'SOUND ON':'SOUND OFF';if(audio.on)audio.ensure()});musicBtn.addEventListener('click',()=>audio.musicToggle());modeBtn.addEventListener('click',()=>{mode=mode==='practice'?'two8':mode==='two8'?'two9':'practice';rack()});guideBtn.addEventListener('click',()=>{guideOn=!guideOn;updateHud();updateAim()});ballInHandBtn.addEventListener('click',()=>{if(ballInHand){ballInHand=false;statusEl.textContent=`PLAYER ${currentPlayer+1} 手球位置確定`;updateHud();updateAim()}});

// Free camera: touch orbit, pinch zoom, 2-finger pan. Desktop: drag orbit, wheel zoom, Shift-drag pan, Ctrl-drag selected axis.
const touches=new Map();let mouseDrag=null,lastPinch=0,lastMid=null;
function canCamera(){return document.body.dataset.phase==='view'&&!ballInHand}
canvas.addEventListener('pointerdown',e=>{if(!canCamera())return;canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,{x:e.clientX,y:e.clientY,px:e.clientX,py:e.clientY});if(e.pointerType==='mouse')mouseDrag={x:e.clientX,y:e.clientY,button:e.button}});
canvas.addEventListener('pointermove',e=>{if(!canCamera()||!touches.has(e.pointerId))return;const t=touches.get(e.pointerId);t.px=t.x;t.py=t.y;t.x=e.clientX;t.y=e.clientY;touches.set(e.pointerId,t);const arr=[...touches.values()];if(arr.length>=2){const a=arr[0],b=arr[1],dist=Math.hypot(a.x-b.x,a.y-b.y),mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(lastPinch){cam.distance=Math.max(cam.minDistance,Math.min(cam.maxDistance,cam.distance-(dist-lastPinch)*.012))}if(lastMid){const dx=mid.x-lastMid.x,dy=mid.y-lastMid.y;const right=new THREE.Vector3().setFromMatrixColumn(camera.matrix,0);const up=new THREE.Vector3(0,1,0);cam.target.addScaledVector(right,-dx*.004*cam.distance).addScaledVector(up,dy*.003*cam.distance)}lastPinch=dist;lastMid=mid;syncCamera();return}if(e.pointerType==='mouse'&&mouseDrag){const dx=e.clientX-mouseDrag.x,dy=e.clientY-mouseDrag.y;mouseDrag.x=e.clientX;mouseDrag.y=e.clientY;if(e.ctrlKey){const k=.004*cam.distance;if(cam.axis==='X')cam.target.x-=dx*k;if(cam.axis==='Y')cam.target.y+=dy*k;if(cam.axis==='Z')cam.target.z+=dx*k}else if(e.shiftKey){const right=new THREE.Vector3().setFromMatrixColumn(camera.matrix,0);cam.target.addScaledVector(right,-dx*.004*cam.distance);cam.target.y+=dy*.003*cam.distance}else{cam.yaw-=dx*.006;cam.pitch=Math.max(.15,Math.min(1.42,cam.pitch+dy*.005))}syncCamera()}else if(arr.length===1&&e.pointerType!=='mouse'){cam.yaw-=(t.x-t.px)*.006;cam.pitch=Math.max(.15,Math.min(1.42,cam.pitch+(t.y-t.py)*.005));syncCamera()}});
function endPointer(e){touches.delete(e.pointerId);mouseDrag=null;if(touches.size<2){lastPinch=0;lastMid=null}}canvas.addEventListener('pointerup',endPointer);canvas.addEventListener('pointercancel',endPointer);canvas.addEventListener('wheel',e=>{if(!canCamera())return;e.preventDefault();cam.distance=Math.max(cam.minDistance,Math.min(cam.maxDistance,cam.distance*(1+Math.sign(e.deltaY)*.08)));syncCamera()},{passive:false});
addEventListener('keydown',e=>{if(['x','y','z','X','Y','Z'].includes(e.key))window.billiardsCamera.axis(e.key.toUpperCase())});

let last=performance.now(),acc=0,wasMoving=false;const fixed=1/120;
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;acc+=dt;if(cueAnim>0){cueAnim+=dt*4.8;if(cueAnim>=1)cueAnim=0}while(acc>=fixed){world.step(fixed);for(const b of balls){if(b.pocketed||b.falling)continue;const v=b.body.velocity,s=Math.hypot(v.x,v.z);if(s<.01){v.x=v.z=0}else{const rr=Math.max(0,1-.23*fixed);v.x*=rr;v.z*=rr}if(Math.abs(v.y)<.025)v.y=0}pocketCheck();acc-=fixed}for(const b of balls){if(!b.pocketed&&!b.falling){b.mesh.position.copy(b.body.position);b.mesh.quaternion.copy(b.body.quaternion)}}animatePocketFalls(dt);const moving=!allStopped();if(wasMoving&&!moving)resolveShot();wasMoving=moving;if(!moving&&!shotActive)updateAim();renderer.render(scene,camera)}requestAnimationFrame(animate);
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();rack();